"""create T003_APPLICATION_EXAMPLES table

Revision ID: 84c0e1cc0146
Revises: f7b031b0aa93
Create Date: 2026-08-28 11:35:21.746127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84c0e1cc0146"
down_revision: Union[str, None] = "f7b031b0aa93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "T003_APPLICATION_EXAMPLES",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["T002_APPLICATIONS.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_T003_APPLICATION_EXAMPLES_application_id"),
        "T003_APPLICATION_EXAMPLES",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_T003_APPLICATION_EXAMPLES_application_id"),
        table_name="T003_APPLICATION_EXAMPLES",
    )
    op.drop_table("T003_APPLICATION_EXAMPLES")
    # ### end Alembic commands ###
