"""create T002_APPLICATIONS table

Revision ID: f7b031b0aa93
Revises: a50c06f0329b
Create Date: 2026-07-14 11:20:50.241202

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b031b0aa93'
down_revision: Union[str, None] = 'a50c06f0329b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "T002_APPLICATIONS",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=160), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("T002_APPLICATIONS")
    # ### end Alembic commands ###
